version: '3'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile 
        ports:
            - "8888:8888"
        volumes:
            - .:/workdir
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]